### PR TITLE
change on interface

### PR DESCRIPTION
**Pull request by amauryfischer**
This is a try in order to change the interface structure, and to adapt it to be easier to use on phone or tablet.
I'm a newbie in code developpment so be free to talk about anything on my code. I'm eager of advice.

### CODE REVIEW

**Comment by RichardPaulAstley** [comment]
Heyah !

Sorry for the late answer. It has been a long and difficult week for me. Always nice to see some improvement for that; I'm gonna check everything this week-end to see if everything can be used for the future.

Thanks

**Comment by amauryfischer** [comment]
Okay no problem :D
Me and my friend are doing a bunch of "improvement" or change.
If you want me to open pull request for this, i can.
I let you have a look on the fork :
https://github.com/amauryfischer/pokemonidle

Those changes are a bit "rought" so that's why i didn't made any pull request for now.

* change on interfarce (this pull request)
* fetch all sprites so we doesn't make any API call (this add 120Mo of image)
* blocked region by region. So now you have to capture 151 pokemon in order to access the next region, and this is done region by region, so the game duration is increased.
* added a button "last" in manage team
* changed pokemon list into pokemon table + added search bar for pokemon table
* changed region list into region table + display pokemon in each route + added search bar for those two. (basically to complete pokedex)

**Comment by amauryfischer** [comment]
oh sorry i forget, and we added master ball^^

**Comment by RichardPaulAstley** [comment]
Well, I'm not gonna lie, I'm looking for your project since a long time now. I didn't know if you wanted to create your own version or Idle or just to complete mine. 

For your stuff, i'll need to see in the next hours (just setting up an event for the moment) and maybe we should find a way to talk more about this, a lot of features are interesting, but some of them i'll go against sadly (the Masterball on the top of the list), but there's a lot of potential, and you both are doing an amazing job ! 

A lot of work to check, but a lot of interesting things. Thanks o/

(If you want to talk, feel free to drop me a PM on reddit, discord or ask for a mail o/)

**Comment by JoshuaPaulBarnard** [comment]
I am starting to work on this game to make alot of improvements that I would like to see, and a properly responsive design is at the top of my list.  I just started working on it, but I have already added jQuery and made it partially responsive.
https://github.com/JoshuaPaulBarnard/PokeIdle

**Comment by amauryfischer** [comment]
its just a note but recently i worked a lot on ReactJs and i though it
would make sth very clear compared to the current code situation wich is
hard to maintain/develop more without a deep understand of all the current
code.

2018-03-15 10:04 GMT+01:00 Joshua Paul Barnard <notifications@github.com>:

**Pull request closed without merging**
