### PR TITLE
Added basics of pokedex

### PR DESCRIPTION
**Pull request by renlok**
Only really saves seen and owned data at the moment and displays a list of all pokemon.
At the moment it will help with your 'Catching only NEW Pokemon' roadmap item. I have plans to add sorting options to it as well as tooltip of where to find them but wanted to show it to you first make sure im not wasting my time

### CODE REVIEW

**Comment by RichardPaulAstley** [comment]
Hey !

Just tried, and it's really a nice job. But, there's something that annoys me a little : The look. The thing that could be done is to make a option to show the Pokedex, like under the "Manage Team" and i'd gladly merge the PR to the game so no waste of your time !

Thanks for contributing to the game !

**Comment by renlok** [comment]
No problem I've sent you a PM via reddit

**Comment by renlok** [comment]
So I have most of the basic functionality working, but it needs some way to resync the owned array when a user starts using a new version

**Comment by RichardPaulAstley** [comment]
Okay here we are 1.9.0 ! Thank you for your work o/ !

**Pull request merged**
